<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Application\DTOs\" />
      <Folder Include="Application\Interfaces\" />
      <Folder Include="Application\Services\" />
      <Folder Include="Domain\Entities\" />
      <Folder Include="Domain\Enums\" />
      <Folder Include="Domain\Interfaces\" />
      <Folder Include="Infrastructure\Data\" />
      <Folder Include="Infrastructure\Identity\" />
      <Folder Include="Infrastructure\Repositories\" />
      <Folder Include="Web\Controllers\" />
      <Folder Include="Web\Middleware\" />
      <Folder Include="Web\Views\" />
      <Folder Include="Web\wwwroot\" />
    </ItemGroup>

</Project>
